name: clipboard
description: Clipboard app made with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_serializable: ^6.1.5
  path_provider: ^2.0.12
  uuid: ^3.0.6
  bitsdojo_window: ^0.1.5
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  # run flutter pub run flutter_launcher_icons
  image_path: "assets/images/appicon.png"
  windows:
    generate: true
    image_path: "assets/images/appicon.png"
    icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/